#!/bin/bash
# Job name
#PBS -N helloc
# Output files
#PBS -o ./mt.o
#PBS -e ./mt.e
# Queue name
#PBS -q short_cpuQ
# Set the maximum wall time
#PBS -l walltime=0:20:00
# Number of nodes, cpus, and amount of memory
#PBS -l select=1:ncpus=8:mem=1gb

# Modules for C
module load gcc91
# Define gcc and g++ to use the version 9.1.0
gcc() {
    gcc-9.1.0 "$@"
}
gcc --version
lscpu
cd project
cpus=$(nproc --all)
dimension=16
for i in $(seq 0 8)
do
  for n in $(seq 1 $cpus);
  do
      export OMP_NUM_THREADS=$n
      echo "NUMBER OF THREADS= $OMP_NUM_THREADS      MATRIX SIZE = $dimension"
      gcc matrix_transposition.c -o mt -fopenmp -O2
      ./mt $dimension
      echo "-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+"
      echo "-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+"
      echo "-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+"
      echo "-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+"
  done
  let dimension="2*dimension"
done